### ISSUE TITLE
MIUI 13, POCO F4 5G GLOBAL 

### ISSUE THREAD

**Issue by cr4shydlo** [NLLAPPS/ACRPhoneHelper#1]
Hello. I have problem with recording calls that i make over bluetooth devices.
I user ACR + ARH, and when i make call with phone, voice is recorded. But when i use bluetooth headphones, it record only my voice. Can i change settings anywhere to record over bluetooth ?

Regards

**Comment by NLLAPPS** [comment]
Hi, is phone rooted?

**Comment by cr4shydlo** [comment]
Hello. No. 
Regards.

**Comment by NLLAPPS** [comment]
This issue tracker is only for APH Magisk module. Recording over Bluetooth on non-rooted devices is not possible since Android 5.
