### ISSUE TITLE
Any workaround for call recording on android 15?

### ISSUE THREAD

**Issue by theintel** [NLLAPPS/ACRPhoneHelper#10]
I just read the readme. It seems Google wants all of the call recording data for itself by restricting access to others. Is there a possibility of finding any workaround to enable call recording on android 15? Or is this the end of the road for call recording?

**Comment by NLLAPPS** [comment]
Do you have Android 15 phone with issue? We have not received any bad feedback yet.

**Comment by theintel** [comment]
Not exactly. I was planning for upgrading to android 15 and thought I should check how many more limitations I might have to face. Does it mean that call recording with APH works fine on android 15?

**Comment by NLLAPPS** [comment]
While we've had no positive feedback, we've had no negative feedback either. Google, might have postponed implementation of kill switch to Android 16 or feature updates to Android 15.

**Comment by theintel** [comment]
OK cool!
