### ISSUE TITLE
Accessibility Service malfunctioning after switching user profiles in Android 13

### ISSUE THREAD

**Issue by Graphite23** [NLLAPPS/ACRPhoneHelper#2]
The bug is reproducible every time I switch to a user profile and back to my owner profile.
The APH service stays running (as seen in Active Apps), however, the Accessibility Service says stopped and malfunctioning.  
I have to toggle off then on, in order to restore the functionality.

During this malfunctioning state, call recording does not work.  The APH app itself has all four green checks and the two option for "prevent APH from being auto closed by you device" are enabled.  Battery optimization is unrestricted and the notification is present.

I had a similar issue with AutoInput from Tasker.  It too had its Accessibility Service stopped after switching profiles.  But Joao recently updated the beta app, and that fixed the problem.  Not sure what he needed to do or how it might work for your Helper app.

**Comment by NLLAPPS** [comment]
It looks like framework bug rather than app but would like to investigate further.  Is this the app? https://play.google.com/store/apps/details?id=com.joaomgcd.autoinput It looks like has not been updated for a long time

**Comment by Graphite23** [comment]
That is the app.  The beta apk was very recently updated.  So only 2.8.1 is on the Play Store.
This is the apk he uploaded for 2.8.3-beta
https://drive.google.com/file/d/1_MCmNfnK4FpFB7HFOgkQxNKbtbmbb8Rs/view

Reddit thread (don't know why he doesn't do Github).
https://www.reddit.com/r/tasker/comments/oz25as/comment/j5sxike/

**Comment by Amandeepyadav85630** [comment]
Unable to record incoming call voices, is there any solution

**Comment by NLLAPPS** [comment]
You may need to enable loud speaker on some phones

**Comment by Amandeepyadav85630** [comment]
SUGGESTION:  may be working on this is an option to IMPLEMENT ACR+ACH
through
• adb(Android debug bridge) in future if possible.
