### ISSUE TITLE
Not working on S23 FE - Android 14  - recordings jumbled/sped up

### ISSUE THREAD

**Issue by nowakdawid** [NLLAPPS/ACRPhoneHelper#6]
Hello,

I downloaded ACR, downloaded the Helper App, turned everything on (accessibility, etc.), the calls are not recorded automatically, so I have to turn on recording manually, but that's fine. What's the real issue are the recording themselves. They all sound like sped up gibberish (poor quaility + audio on what it feels like 10x speed). I had the same effect with Cube ACR and its helper app as well.

It's like it was anynomizing the calls automatically if it detects calls being recorded. And I've tried all the input sources via the Cube ACR app. It's either not recording, the recordings are silent or it's this jumbled mess

I have found one other person with this exact issue, so maybe it's not something only limited to my unit.

Any help would be much appreciated :)

**Comment by NLLAPPS** [comment]
It may not be possible to record properly on some phones.
You can:

- Remove any other call recording apps and turn of ACR Call Recorder Red (if it is installed).
- Try changing recording delay and Audio  Encoder in Recording settings.
- Try adjusting Recording Audio Gain under Call Recording Settings
- Try enabling loud speaker to see if it helps.
- Make sure you are not using any headphones of Bluetooth headset.
- Make sure Wi-Fi calling is disabled.
- Open Accessibility Settings of Your phone and Toggle ACR Phone Helper (APH) Off and then On again.
- Keep ACR Phone on the screen. Some phones can only record when ACR Phone is on the screen and screen is on.
- Do not close ACR Phone from recent apps and appy settigns from https://dontkillmyapp.com

Unfortunately, there is nothing we can do if above information doesn’t help. This issue will be same with all call recording apps.
