### ISSUE TITLE
Unable to record. Are you using other call recording apps?

### ISSUE THREAD

**Issue by odiseo123** [NLLAPPS/ACRPhoneHelper#7]
Hi Team.
First of all thanks for the great tool. I have been using ARC on my old phone quite reliably for some time.
I upgraded my rooted phone (Magysk) to Android 12 and have been trying to get ACR Phone+APH working without success. My APH settings look like:
![Screenshot_20240522-193032_APH - Copy](https://github.com/NLLAPPS/ACRPhoneHelper/assets/18690090/af7622ba-f2a0-4eac-8f4f-d8c25718298f)
In ACR Phone, *Call recording*, *Automatic recording* and *Premium with adverts* are enabled.
When I get a call, ACR Phone pops a notification "Unable to record. Are you using other call recording apps?"
ACR Phone is the default phone app and no other call recording apps have been installed (fresh ROM).

From the logs:

> [2024-05-22 17:38:12.341] [CB_RoleHelper] isDefaultDialerApi29: true
> [2024-05-22 17:38:12.344] [CB_RoleHelper] ROLE_CALL_SCREENING  isRoleAvailable: true isDefault: true
> [2024-05-22 17:38:12.347] [CB_CLog] App
> ---------
> Version: 0.335-playStore-NoAccessibility-arm8 (10335)
> Default phone app: true
> Default call screening app: true
> Has contact read permission: true
> Has contact write permission: true
> Call blocking enabled: true
> Call recording enabled: true
> Call announcement enabled: false
> NLLApps Online enabled: false
> Enhanced Caller ID enabled: false
> 
> System
> ---------
> Android version: 12
> Manufacturer: samsung
> Model: [redacted]
> Hardware: [redacted]
> Product: [redacted]
> Screen height Dp : [redacted]
> Screen width Dp : [redacted]

The first occurrence of the error:
> [2024-05-22 17:38:46.140] [CB_APHRecorder] recorderConfig.recorderListener.onRecordingStateChange() -> newState: Error(recorderError=RemoteError, exception=java.lang.Exception: Remote error)
> [2024-05-22 17:38:46.140] [CB_CallListManager] recordingState changed -> multiCallRecordingHandler recording state is changed to Error(recorderError=RemoteError, exception=java.lang.Exception: Remote error) updating all calls

Which then trickles down to processes [CB_CR_RemoterServiceController], [CB_RecordingErrorNotification], [CB_CallRecordingController], and [CB_CallInfo] with the same generic "exception=java.lang.Exception" error.

I can provide the full redacted log, but wondering if the above is enough for you to pinpoint the issue and/or suggest a fix.

Thanks again for the tool and your time.

**Comment by NLLAPPS** [comment]
Hi, are you using APH Magisk module? On a rooted phone APH Magisk should be used

**Comment by odiseo123** [comment]
Thanks for the prompt reply.
Yes, I am using this: https://acr.app/aph-magisk-module.zip
![image](https://github.com/NLLAPPS/ACRPhoneHelper/assets/18690090/d7bc3a9e-6d08-43e2-9b60-362252c3481b)

I believe I followed the instructions: "Rooted phones can install APH Magisk Module. APH Magisk Module provides real two-way call recording including Bluetooth/Headphones. Please make sure to uninstall normal APH before installing APH Magisk Module."
I had no "normal APH" to uninstall as it was a fresh ROM.
I installed ACR Phone, then used Magisk to Install the APH Magisk Module. Rebooted as requested by Magisk.
I assumed all went well based on this image:
![image](https://github.com/NLLAPPS/ACRPhoneHelper/assets/18690090/005be4b0-25b0-4e78-b19a-cc717536c67f)

However, when called, I get the "Unable to record. Are you using other call recording apps?" notification

**Comment by NLLAPPS** [comment]
Please go to APH settings and tap on version then tap on Debug. Start debug logging. Replicate the issue while debug is enabled, come back open debug logging and select send to send debug logs to us.

**Comment by odiseo123** [comment]
I have the logs. Do you want me to attach those here or is there an email address to send them to?

**Comment by NLLAPPS** [comment]
They may contain private info, please use the Debug log screen to email them.

**Comment by odiseo123** [comment]
I thought the debug screen would send them to you automatically, however, hitting "Send" generates a ZIP file which can either downloaded or emailed manually. They do not seem to be sent automatically. 

Start of logging:
![image](https://github.com/NLLAPPS/ACRPhoneHelper/assets/18690090/fa12ed80-e34a-4f83-a99e-0913c8e47f14)

After calling, the logs are generated and "Send" becomes available:
![image](https://github.com/NLLAPPS/ACRPhoneHelper/assets/18690090/3ad939d3-3a43-442e-a260-45513ed1c8fe)

Hitting "Send", creates a ZIP to be downloaded or emailed manually:
![image](https://github.com/NLLAPPS/ACRPhoneHelper/assets/18690090/4b0025ab-f774-4c5c-a0ed-7bfa2a067053)

Thanks for your patience.

**Comment by odiseo123** [comment]
Got it, I was getting confused. Done just now. Thx

**Comment by NLLAPPS** [comment]
Hi, you need to select Send and use your email client to send attachment as normal email.

**Comment by NLLAPPS** [comment]
Nothing received so far

**Comment by NLLAPPS** [comment]
I have received them. Something on your phone preventing call recording. It could be issues with the ROM if it is a custom one. Try using MediCodec Recording engine under ACR phone recording Settings, if that fails then there is nothing else we can do unfortunately.

**Comment by odiseo123** [comment]
Thanks. I tried changing the "Audio encoder" default option to "MediaCodec" and "MediaRecorder". No luck.
Next weekend, I will try again a fresh ROM re-install vs stock ROM to confirm your suspicion.
In the interim, does any ARC components depend on Google Play Services? The current ROM is de-googled and runs microG instead.

**Comment by odiseo123** [comment]
Hi there. I decided against re-flashing stock. However I did try Basic Call Recorder (BCR) on Magisk on a fresh install of the custom ROM. This also failed, albeit with a more interesting log:
![image](https://github.com/NLLAPPS/ACRPhoneHelper/assets/18690090/8e986f55-0644-455d-846b-692823d383f0)
So, you are likely correct in that there is a bug/limitation with this ROM.
I will follow it up on XDA.

Thanks for the great support.

**Comment by odiseo123** [comment]
Hi @NLLAPPS 
Just an FYI in case it can be useful in the future.
After following a tip on [XDA](https://xdaforums.com/t/lineageos-19-1-android-12l-signature-spoofing-ota-updates-for-s7-edge-exynos.4369001/post-89528936) I got another call recording app going. So indeed there may be something funky in this ROM that prevents the "usual" recording method from working (ACR Phone, Cube ACR and BCR failed for me on this ROM), but I guess it is not impossible (i.e. it's not that some core function is broken/missing from the ROM).
I recognize this is likely an edge case, not worth chasing after. 
Thanks again for the app and effort.
