### ISSUE TITLE
Problem parsing android 9.0 huawei

### ISSUE THREAD

**Issue by zrodrps** [NLLAPPS/ACRPhoneHelper#9]
I couldn't install get the parsing error. Tried downloading from nllappstore and huawei gallery (not avaiable anymore) I've got android v. 9 on an older huawei shouldnt that work? Fk these google mfs restricting MY phone reason I'm using android over iphone :(

**Comment by NLLAPPS** [comment]
APH can only be used on Android 10 and above. You do not need APH on Android 9.
